package com.team9.questgame.Entities.Effects;

public enum EffectState {
    INACTIVE,
    ACTIVATED,
    TRIGGER_TARGET_SELECTION,
    TRIGGER_TARGET_SELECTION_REQUEST_SUBMITTED,
    TRIGGER_EFFECT_RESOLUTION,
    TARGET_SELECTION,
    EFFECT_RESOLUTION,
    EFFECT_RESOLUTION_PLAYER_RESPONSE,
    RESOLVED,
    TRIGGER_RESOLVED
}
