package com.team9.questgame.Entities.Effects;

public enum EffectState {
    INACTIVE,
    ACTIVATED,
    TARGET_SELECTION_ON_TRIGGER,
    TRIGGERED,
    TARGET_SELECTION,
    EFFECT_RESOLUTION,
    EFFECT_RESOLUTION_WAIT_FOR_PLAYER_DISCARDS,
    RESOLVED
}
