const CardImages = {
    Back_Adventure: "./Assets/Adventure Deck (346x470)/Adventure Deck Card Back.png",
    Ally_KingArthur: "./Assets/Adventure Deck (346x470)/Ally - King Arthur.png",
    Ally_KingPellinore: "./Assets/Adventure Deck (346x470)/Ally - King Pellinore.png",
    Ally_Merlin: "./Assets/Adventure Deck (346x470)/Ally - Merlin.png",
    Ally_QueenGuinevere: "./Assets/Adventure Deck (346x470)/Ally - Queen Guinevere.png",
    Ally_SirGalahad: "./Assets/Adventure Deck (346x470)/Ally - Sir Galahad.png",
    Ally_SirGawain: "./Assets/Adventure Deck (346x470)/Ally - Sir Gawain.png",
    Ally_SirLancelot: "./Assets/Adventure Deck (346x470)/Ally - Sir Lancelot.png",
    Ally_SirPercival: "./Assets/Adventure Deck (346x470)/Ally - Sir Percival.png",
    Ally_SirTristan: "./Assets/Adventure Deck (346x470)/Ally - Sir Tristan.png",
    Ally_QueenIseult: "./Assets/Adventure Deck (346x470)/Ally - Queen Iseult.png",
    Amour: "./Assets/Adventure Deck (346x470)/Amour.png",
    Foe_Boar: "./Assets/Adventure Deck (346x470)/Foe - Boar.png",
    Foe_EvilKnight: "./Assets/Adventure Deck (346x470)/Foe - Evil Knight.png",
    Foe_GreenKnight: "./Assets/Adventure Deck (346x470)/Foe - Green Knight.png",
    Foe_RobberKnight: "./Assets/Adventure Deck (346x470)/Foe - Robber Knight.png",
    Foe_SaxonKnight: "./Assets/Adventure Deck (346x470)/Foe - Saxon Knight.png",
    Foe_Saxons: "./Assets/Adventure Deck (346x470)/Foe - Saxons.png",
    Foe_Thieves: "./Assets/Adventure Deck (346x470)/Foe - Thieves.png",
    Test_TestOfMorganLeFey: "./Assets/Adventure Deck (346x470)/Test - Test of Morgan Le Fey.png",
    Test_TestOfTemptation: "./Assets/Adventure Deck (346x470)/Test - Test of Temptation.png",
    Test_TestOfTheQuestingBeast: "./Assets/Adventure Deck (346x470)/Test - Test of the Questing Beast.png",
    Test_TestOfValor: "./Assets/Adventure Deck (346x470)/Test - Test of Valor.png",
    Weapon_BattleAx: "./Assets/Adventure Deck (346x470)/Weapon - Battle-ax.png",
    Weapon_Dagger: "./Assets/Adventure Deck (346x470)/Weapon - Dagger.png",
    Weapon_Excalibur: "./Assets/Adventure Deck (346x470)/Weapon - Excalibur.png",
    Weapon_Horse: "./Assets/Adventure Deck (346x470)/Weapon - Horse.png",
    Weapon_Lance: "./Assets/Adventure Deck (346x470)/Weapon - Lance.png",
    Weapon_Sword: "./Assets/Adventure Deck (346x470)/Weapon - Sword.png",
    Rank_ChampionKnight: "./Assets/Rank Deck (327x491)/Rank - Champion Knight.png",
    Rank_Knight: "./Assets/Rank Deck (327x491)/Rank - Knight.png",
    Rank_Squire: "./Assets/Rank Deck (327x491)/Rank - Squire.png",
    Shield_1: "./Assets/Shield Cards (346x346)/Shield 1.png",
    Shield_2: "./Assets/Shield Cards (346x346)/Shield 2.png",
    Shield_3: "./Assets/Shield Cards (346x346)/Shield 3.png",
    Shield_4: "./Assets/Shield Cards (346x346)/Shield 4.png",
    Shield_5: "./Assets/Shield Cards (346x346)/Shield 5.png",
    Shield_6: "./Assets/Shield Cards (346x346)/Shield 6.png",
    Shield_7: "./Assets/Shield Cards (346x346)/Shield 7.png",
    Shield_8: "./Assets/Shield Cards (346x346)/Shield 8.png",
    Shield_9: "./Assets/Shield Cards (346x346)/Shield 9.png",
    Event_ChivalrousDeed: "./Assets/Story Deck (327x491)/Event - Chivalrous Deed.png",
    Event_CourtCalledToCamelot: "./Assets/Story Deck (327x491)/Event - Court Called to Camelot.png",
    Event_KingsCallToArms: "./Assets/Story Deck (327x491)/Event - Kings Call to Arms.png",
    Event_KingsRecognition: "./Assets/Story Deck (327x491)/Event - Kings Recognition.png",
    Event_Plague: "./Assets/Story Deck (327x491)/Event - Plague.png",
    Event_Pox: "./Assets/Story Deck (327x491)/Event - Pox.png",
    Event_ProsperityThroughtTheRelm: "./Assets/Story Deck (327x491)/Event - Prosperity Throught the Relm.png",
    Event_QueensFavor: "./Assets/Story Deck (327x491)/Event - Queens Favor.png",
    Quest_BoarHunt: "./Assets/Story Deck (327x491)/Quest - Boar Hunt.png",
    Quest_DefendTheQueensHonor: "./Assets/Story Deck (327x491)/Quest - Defend the Queen's Honor.png",
    Quest_JourneyThroughTheEnchantedForest: "./Assets/Story Deck (327x491)/Quest - Journey through the Enchanted Forest.png",
    Quest_RepelTheSaxonRaiders: "./Assets/Story Deck (327x491)/Quest - Repel the Saxon Raiders.png",
    Quest_RescueTheFairMaiden: "./Assets/Story Deck (327x491)/Quest - Rescue the Fair Maiden.png",
    Quest_SearchForTheHolyGrail: "./Assets/Story Deck (327x491)/Quest - Search for the Holy Grail.png",
    Quest_SearchForTheQuestingBeast: "./Assets/Story Deck (327x491)/Quest - Search for the Questing Beast.png",
    Quest_SlayTheDragon: "./Assets/Story Deck (327x491)/Quest - Slay the Dragon.png",
    Quest_TestOfTheGreenKnight: "./Assets/Story Deck (327x491)/Quest - Test of the Green Knight.png",
    Quest_VanquishKingArthursEnemies: "./Assets/Story Deck (327x491)/Quest - Vanquish King Arthur's Enemies.png",
    Tournament_AtCamelot: "./Assets/Story Deck (327x491)/Tournament - At Camelot.png",
    Tournament_AtOrkney: "./Assets/Story Deck (327x491)/Tournament - At Orkney.png",
    Tournament_AtTintagel: "./Assets/Story Deck (327x491)/Tournament - At Tintagel.png",
    Tournament_AtYork: "./Assets/Story Deck (327x491)/Tournament - At York.png",
  }
  export default CardImages;